export interface RandomizerItemEntry {
  readonly name: string;
  readonly type: ItemType;
}

export enum ItemType {
  Item,
  Consumable,
  Song,
  Quest,
  BossKey,
  GanonBossKey,
  SmallKey,
  Map,
  Compass,
  Meta,
  Trap,
}

// prettier-ignore
export const ItemTable: ReadonlyMap<number, RandomizerItemEntry> = new Map([
  // Meta Items
  [0x00, { name: "Nothing",                             type: ItemType.Meta }],

  // Equipment and Inventory Items (Excluding Bottles and Trade Sequence Items)
  [0x57, { name: "Biggoron Sword",                      type: ItemType.Item }],
  [0x06, { name: "Boomerang",                           type: ItemType.Item }],
  [0x89, { name: "Bombchus",                            type: ItemType.Item }],
  [0x82, { name: "Bomb Bag",                            type: ItemType.Item }],
  [0x87, { name: "Deku Nut Capacity",                   type: ItemType.Item }],
  [0x29, { name: "Deku Shield",                         type: ItemType.Item }],
  [0x88, { name: "Deku Stick Capacity",                 type: ItemType.Item }],
  [0x5C, { name: "Din's Fire",                          type: ItemType.Item }],
  [0xB8, { name: "Double Defense",                      type: ItemType.Item }],
  [0x83, { name: "Fairy Bow",                           type: ItemType.Item }],
  [0x5D, { name: "Farore's Wind",                       type: ItemType.Item }],
  [0x58, { name: "Fire Arrows",                         type: ItemType.Item }],
  [0x28, { name: "Giant's Knife",                       type: ItemType.Item }],
  [0x2C, { name: "Goron Tunic",                         type: ItemType.Item }],
  [0x2F, { name: "Hover Boots",                         type: ItemType.Item }],
  [0x2A, { name: "Hylian Shield",                       type: ItemType.Item }],
  [0x59, { name: "Ice Arrows",                          type: ItemType.Item }],
  [0x2E, { name: "Iron Boots",                          type: ItemType.Item }],
  [0x27, { name: "Kokiri Sword",                        type: ItemType.Item }],
  [0x0A, { name: "Lens of Truth",                       type: ItemType.Item }],
  [0x5A, { name: "Light Arrows",                        type: ItemType.Item }],
  [0xC9, { name: "Magic Bean Pack",                     type: ItemType.Item }],
  [0x0D, { name: "Megaton Hammer",                      type: ItemType.Item }],
  [0x2B, { name: "Mirror Shield",                       type: ItemType.Item }],
  [0x5E, { name: "Nayru's Love",                        type: ItemType.Item }],
  [0x80, { name: "Progressive Hookshot",                type: ItemType.Item }],
  [0x8B, { name: "Progressive Ocarina",                 type: ItemType.Item }],
  [0x8A, { name: "Progressive Magic",                   type: ItemType.Item }],
  [0x86, { name: "Progressive Scale",                   type: ItemType.Item }],
  [0x81, { name: "Progressive Strength",                type: ItemType.Item }],
  [0x85, { name: "Progressive Wallet",                  type: ItemType.Item }],
  [0x84, { name: "Fairy Slingshot",                     type: ItemType.Item }],
  [0x2D, { name: "Zora Tunic",                          type: ItemType.Item }],

  // Bottles
  [0x0F, { name: "Bottle (Empty)",                      type: ItemType.Item }],
  [0x93, { name: "Bottle (Big Poe)",                    type: ItemType.Item }],
  [0x91, { name: "Bottle (Blue Fire)",                  type: ItemType.Item }],
  [0x8E, { name: "Bottle (Blue Potion)",                type: ItemType.Item }],
  [0x92, { name: "Bottle (Bugs)",                       type: ItemType.Item }],
  [0x8F, { name: "Bottle (Fairy)",                      type: ItemType.Item }],
  [0x90, { name: "Bottle (Fish)",                       type: ItemType.Item }],
  [0x8D, { name: "Bottle (Green Potion)",               type: ItemType.Item }],
  [0x14, { name: "Bottle (Lon Lon Milk)",               type: ItemType.Item }],
  [0x94, { name: "Bottle (Poe)",                        type: ItemType.Item }],
  [0x8C, { name: "Bottle (Red Potion)",                 type: ItemType.Item }],
  [0x15, { name: "Bottle (Ruto's Letter)",              type: ItemType.Item }],

  // Child Trading Sequence
  [0x47, { name: "Weird Egg",                           type: ItemType.Item }],
  [0x0B, { name: "Zelda's Letter",                      type: ItemType.Item }],
  [0x1A, { name: "Keaton Mask",                         type: ItemType.Item }],
  [0x17, { name: "Skull Mask",                          type: ItemType.Item }],
  [0x18, { name: "Spooky Mask",                         type: ItemType.Item }],
  [0x1B, { name: "Bunny Hood",                          type: ItemType.Item }],
  [0x1C, { name: "Mask of Truth",                       type: ItemType.Item }],
  [0x51, { name: "Goron Mask",                          type: ItemType.Item }],
  [0x52, { name: "Zora Mask",                           type: ItemType.Item }],
  [0x53, { name: "Gerudo Mask",                         type: ItemType.Item }],

  // Adult Trading Sequence
  [0x1D, { name: "Pocket Egg",                          type: ItemType.Item }],
  [0x1E, { name: "Pocket Cucco",                        type: ItemType.Item }],
  [0x0E, { name: "Cojiro",                              type: ItemType.Item }],
  [0x1F, { name: "Odd Mushroom",                        type: ItemType.Item }],
  [0x20, { name: "Odd Potion",                          type: ItemType.Item }],
  [0x21, { name: "Poacher's Saw",                       type: ItemType.Item }],
  [0x22, { name: "Broken Goron Sword",                  type: ItemType.Item }],
  [0x23, { name: "Prescription",                        type: ItemType.Item }],
  [0x24, { name: "Eyeball Frog",                        type: ItemType.Item }],
  [0x25, { name: "Eye Drops",                           type: ItemType.Item }],
  [0x26, { name: "Claim Check",                         type: ItemType.Item }],

  // Songs
  [0xC1, { name: "Zelda's Lullaby",                     type: ItemType.Song }],
  [0xC3, { name: "Saria's Song",                        type: ItemType.Song }],
  [0xC2, { name: "Epona's Song",                        type: ItemType.Song }],
  [0xC4, { name: "Sun's Song",                          type: ItemType.Song }],
  [0xC5, { name: "Song of Time",                        type: ItemType.Song }],
  [0xC6, { name: "Song of Storms",                      type: ItemType.Song }],
  [0xBB, { name: "Minuet of Forest",                    type: ItemType.Song }],
  [0xBC, { name: "Bolero of Fire",                      type: ItemType.Song }],
  [0xBD, { name: "Serenade of Water",                   type: ItemType.Song }],
  [0xBE, { name: "Requiem of Spirit",                   type: ItemType.Song }],
  [0xBF, { name: "Nocturne of Shadow",                  type: ItemType.Song }],
  [0xC0, { name: "Prelude of Light",                    type: ItemType.Song }],

  // Quest Items and Permanent Link Upgrades
  [0x3D, { name: "Heart Container",                     type: ItemType.Quest }],
  [0x4F, { name: "Boss Heart Container",                type: ItemType.Quest }],
  [0x3E, { name: "Heart Piece",                         type: ItemType.Quest }],
  [0x76, { name: "Heart Piece (Treasure)",              type: ItemType.Quest }],
  [0x3A, { name: "Gerudo Membership Card",              type: ItemType.Item }],
  [0x5B, { name: "Gold Skulltula Token",                type: ItemType.Quest }],
  [0x39, { name: "Stone of Agony",                      type: ItemType.Item }],
  [0xCA, { name: "Triforce Piece",                      type: ItemType.Quest }],

  // Consumables
  [0x49, { name: "Arrows (5)",                          type: ItemType.Consumable }],
  [0x4A, { name: "Arrows (10)",                         type: ItemType.Consumable }],
  [0x4B, { name: "Arrows (30)",                         type: ItemType.Consumable }],
  [0x6A, { name: "Bombchus (5)",                        type: ItemType.Consumable }],
  [0x03, { name: "Bombchus (10)",                       type: ItemType.Consumable }],
  [0x6B, { name: "Bombchus (20)",                       type: ItemType.Consumable }],
  [0x01, { name: "Bombs (5)",                           type: ItemType.Consumable }],
  [0x66, { name: "Bombs (10)",                          type: ItemType.Consumable }],
  [0x67, { name: "Bombs (20)",                          type: ItemType.Consumable }],
  [0x02, { name: "Deku Nuts (5)",                       type: ItemType.Consumable }],
  [0x64, { name: "Deku Nuts (10)",                      type: ItemType.Consumable }],
  [0x69, { name: "Deku Seeds (30)",                     type: ItemType.Consumable }],
  [0x07, { name: "Deku Stick (1)",                      type: ItemType.Consumable }],
  [0x48, { name: "Recovery Heart",                      type: ItemType.Consumable }],
  [0x72, { name: "Rupee (Treasure)",                    type: ItemType.Consumable }],
  [0x4C, { name: "Rupee (1)",                           type: ItemType.Consumable }],
  [0x4D, { name: "Rupees (5)",                          type: ItemType.Consumable }],
  [0x4E, { name: "Rupees (20)",                         type: ItemType.Consumable }],
  [0x55, { name: "Rupees (50)",                         type: ItemType.Consumable }],
  [0x56, { name: "Rupees (200)",                        type: ItemType.Consumable }],

  // Boss Keys
  [0x3F, { name: "Boss Key",                            type: ItemType.BossKey }],
  [0x95, { name: "Boss Key (Forest Temple)",            type: ItemType.BossKey }],
  [0x96, { name: "Boss Key (Fire Temple)",              type: ItemType.BossKey }],
  [0x97, { name: "Boss Key (Water Temple)",             type: ItemType.BossKey }],
  [0x98, { name: "Boss Key (Spirit Temple)",            type: ItemType.BossKey }],
  [0x99, { name: "Boss Key (Shadow Temple)",            type: ItemType.BossKey }],
  [0x9A, { name: "Boss Key (Ganon's Castle)",           type: ItemType.GanonBossKey }],

  // Small Keys
  [0x42, { name: "Small Key",                           type: ItemType.SmallKey }],
  [0xAF, { name: "Small Key (Forest Temple)",           type: ItemType.SmallKey }],
  [0xB0, { name: "Small Key (Fire Temple)",             type: ItemType.SmallKey }],
  [0xB1, { name: "Small Key (Water Temple)",            type: ItemType.SmallKey }],
  [0xB2, { name: "Small Key (Spirit Temple)",           type: ItemType.SmallKey }],
  [0xB3, { name: "Small Key (Shadow Temple)",           type: ItemType.SmallKey }],
  [0xB4, { name: "Small Key (Bottom of the Well)",      type: ItemType.SmallKey }],
  [0xB5, { name: "Small Key (Gerudo Training Grounds)", type: ItemType.SmallKey }],
  [0xB6, { name: "Small Key (Gerudo Fortress)",         type: ItemType.SmallKey }],
  [0xB7, { name: "Small Key (Ganon's Castle)",          type: ItemType.SmallKey }],

  // Maps
  [0x41, { name: "Map",                                 type: ItemType.Map }],
  [0xA5, { name: "Map (Deku Tree)",                     type: ItemType.Map }],
  [0xA6, { name: "Map (Dodongo's Cavern)",              type: ItemType.Map }],
  [0xA7, { name: "Map (Jabu Jabu's Belly)",             type: ItemType.Map }],
  [0xA8, { name: "Map (Forest Temple)",                 type: ItemType.Map }],
  [0xA9, { name: "Map (Fire Temple)",                   type: ItemType.Map }],
  [0xAA, { name: "Map (Water Temple)",                  type: ItemType.Map }],
  [0xAB, { name: "Map (Spirit Temple)",                 type: ItemType.Map }],
  [0xAC, { name: "Map (Shadow Temple)",                 type: ItemType.Map }],
  [0xAD, { name: "Map (Bottom of the Well)",            type: ItemType.Map }],
  [0xAE, { name: "Map (Ice Cavern)",                    type: ItemType.Map }],
  
  // Compasses
  [0x40, { name: "Compass",                             type: ItemType.Compass }],
  [0x9B, { name: "Compass (Deku Tree)",                 type: ItemType.Compass }],
  [0x9C, { name: "Compass (Dodongo's Cavern)",          type: ItemType.Compass }],
  [0x9D, { name: "Compass (Jabu Jabu's Belly)",         type: ItemType.Compass }],
  [0x9E, { name: "Compass (Forest Temple)",             type: ItemType.Compass }],
  [0x9F, { name: "Compass (Fire Temple)",               type: ItemType.Compass }],
  [0xA0, { name: "Compass (Water Temple)",              type: ItemType.Compass }],
  [0xA1, { name: "Compass (Spirit Temple)",             type: ItemType.Compass }],
  [0xA2, { name: "Compass (Shadow Temple)",             type: ItemType.Compass }],
  [0xA3, { name: "Compass (Bottom of the Well)",        type: ItemType.Compass }],
  [0xA4, { name: "Compass (Ice Cavern)",                type: ItemType.Compass }],

  // Misc.
  [0x50, { name: "Milk",                                type: ItemType.Consumable }],
  [0x7C, { name: "Ice Trap",                            type: ItemType.Trap }],
  [0x16, { name: "Magic Beans",                         type: ItemType.Consumable }],
]);
